commodities = [
    {'value': 451, 'name': 'Absinthe'},
    {'value': 137, 'name': 'Ajwan'},
    {'value': 281, 'name': 'Alasande Gram'},
    {'value': 325, 'name': 'Almond(Badam)'},
    {'value': 166, 'name': 'Alsandikai'},
    {'value': 86, 'name': 'Amaranthus'},
    {'value': 130, 'name': 'Ambada Seed'},
    {'value': 417, 'name': 'Ambady/Mesta'},
    {'value': 355, 'name': 'Amla(Nelli Kai)'},
    {'value': 102, 'name': 'Amphophalus'},
    {'value': 419, 'name': 'Amranthas Red'},
    {'value': 209, 'name': 'Antawala'},
    {'value': 379, 'name': 'Anthorium'},
    {'value': 17, 'name': 'Apple'},
    {'value': 326, 'name': 'Apricot(Jardalu/Khumani)'},
    {'value': 140, 'name': 'Arecanut(Betelnut/Supari)'},
    {'value': 49, 'name': 'Arhar (Tur/Red Gram)(Whole)'},
    {'value': 260, 'name': 'Arhar Dal(Tur Dal)'},
    {'value': 444, 'name': 'Asalia'},
    {'value': 505, 'name': 'Asgand'},
    {'value': 83, 'name': 'Ashgourd'},
    {'value': 506, 'name': 'Ashoka'},
    {'value': 443, 'name': 'Ashwagandha'},
    {'value': 434, 'name': 'Asparagus'},
    {'value': 232, 'name': 'Astera'},
    {'value': 507, 'name': 'Atis'},
    {'value': 269, 'name': 'Avare Dal'},
    {'value': 418, 'name': 'Bael'},
    {'value': 491, 'name': 'Bajji chilli'},
    {'value': 28, 'name': 'Bajra(Pearl Millet/Cumbu)'},
    {'value': 274, 'name': 'Balekai'},
    {'value': 482, 'name': 'balsam'},
    {'value': 204, 'name': 'Bamboo'},
    {'value': 19, 'name': 'Banana'},
    {'value': 90, 'name': 'Banana - Green'},
    {'value': 483, 'name': 'Banana flower'},
    {'value': 485, 'name': 'Banana Leaf'},
    {'value': 484, 'name': 'Banana stem'},
    {'value': 29, 'name': 'Barley (Jau)'},
    {'value': 435, 'name': 'basil'},
    {'value': 321, 'name': 'Bay leaf (Tejpatta)'},
    {'value': 94, 'name': 'Beans'},
    {'value': 262, 'name': 'Beaten Rice'},
    {'value': 157, 'name': 'Beetroot'},
    {'value': 508, 'name': 'Behada'},
    {'value': 263, 'name': 'Bengal Gram Dal (Chana Dal)'},
    {'value': 6, 'name': 'Bengal Gram(Gram)(Whole)'},
    {'value': 357, 'name': 'Ber(Zizyphus/Borehannu)'},
    {'value': 143, 'name': 'Betal Leaves'},
    {'value': 41, 'name': 'Betelnuts'},
    {'value': 85, 'name': 'Bhindi(Ladies Finger)'},
    {'value': 448, 'name': 'Bhui Amlaya'},
    {'value': 113, 'name': 'Big Gram'},
    {'value': 51, 'name': 'Binoula'},
    {'value': 81, 'name': 'Bitter gourd'},
    {'value': 8, 'name': 'Black Gram (Urd Beans)(Whole)'},
    {'value': 264, 'name': 'Black Gram Dal (Urd Dal)'},
    {'value': 38, 'name': 'Black pepper'},
    {'value': 380, 'name': 'BOP'},
    {'value': 189, 'name': 'Borehannu'},
    {'value': 82, 'name': 'Bottle gourd'},
    {'value': 449, 'name': 'Brahmi'},
    {'value': 290, 'name': 'Bran'},
    {'value': 497, 'name': 'Bread Fruit'},
    {'value': 35, 'name': 'Brinjal'},
    {'value': 487, 'name': 'Brocoli'},
    {'value': 293, 'name': 'Broken Rice'},
    {'value': 320, 'name': 'Broomstick(Flower Broom)'},
    {'value': 214, 'name': 'Bull'},
    {'value': 284, 'name': 'Bullar'},
    {'value': 224, 'name': 'Bunch Beans'},
    {'value': 272, 'name': 'Butter'},
    {'value': 416, 'name': 'buttery'},
    {'value': 154, 'name': 'Cabbage'},
    {'value': 480, 'name': 'Calendula'},
    {'value': 215, 'name': 'Calf'},
    {'value': 354, 'name': 'Camel Hair'},
    {'value': 205, 'name': 'Cane'},
    {'value': 164, 'name': 'Capsicum'},
    {'value': 40, 'name': 'Cardamoms'},
    {'value': 375, 'name': 'Carnation'},
    {'value': 153, 'name': 'Carrot'},
    {'value': 238, 'name': 'Cashew Kernnel'},
    {'value': 36, 'name': 'Cashewnuts'},
    {'value': 270, 'name': 'Castor Oil'},
    {'value': 123, 'name': 'Castor Seed'},
    {'value': 34, 'name': 'Cauliflower'},
    {'value': 188, 'name': 'Chakotha'},
    {'value': 438, 'name': 'Chandrashoor'},
    {'value': 169, 'name': 'Chapparad Avare'},
    {'value': 241, 'name': 'Chennangi (Whole)'},
    {'value': 295, 'name': 'Chennangi Dal'},
    {'value': 328, 'name': 'Cherry'},
    {'value': 71, 'name': 'Chikoos(Sapota)'},
    {'value': 26, 'name': 'Chili Red'},
    {'value': 88, 'name': 'Chilly Capsicum'},
    {'value': 509, 'name': 'Chironji'},
    {'value': 167, 'name': 'Chow Chow'},
    {'value': 402, 'name': 'Chrysanthemum'},
    {'value': 231, 'name': 'Chrysanthemum(Loose)'},
    {'value': 316, 'name': 'Cinamon(Dalchini)'},
    {'value': 467, 'name': 'cineraria'},
    {'value': 478, 'name': 'Clarkia'},
    {'value': 105, 'name': 'Cloves'},
    {'value': 80, 'name': 'Cluster beans'},
    {'value': 315, 'name': 'Coca'},
    {'value': 368, 'name': 'Cock'},
    {'value': 104, 'name': 'Cocoa'},
    {'value': 138, 'name': 'Coconut'},
    {'value': 266, 'name': 'Coconut Oil'},
    {'value': 112, 'name': 'Coconut Seed'},
    {'value': 45, 'name': 'Coffee'},
    {'value': 318, 'name': 'Colacasia'},
    {'value': 129, 'name': 'Copra'},
    {'value': 43, 'name': 'Coriander(Leaves)'},
    {'value': 108, 'name': 'Corriander seed'},
    {'value': 472, 'name': 'Cossandra'},
    {'value': 15, 'name': 'Cotton'},
    {'value': 99, 'name': 'Cotton Seed'},
    {'value': 212, 'name': 'Cow'},
    {'value': 92, 'name': 'Cowpea (Lobia/Karamani)'},
    {'value': 89, 'name': 'Cowpea(Veg)'},
    {'value': 159, 'name': 'Cucumbar(Kheera)'},
    {'value': 42, 'name': 'Cummin Seed(Jeera)'},
    {'value': 486, 'name': 'Curry Leaf'},
    {'value': 352, 'name': 'Custard Apple (Sharifa)'},
    {'value': 382, 'name': 'Daila(Chandni)'},
    {'value': 91, 'name': 'Dal (Avare)'},
    {'value': 273, 'name': 'Dalda'},
    {'value': 410, 'name': 'Delha'},
    {'value': 69, 'name': 'Dhaincha'},
    {'value': 442, 'name': 'dhawai flowers'},
    {'value': 476, 'name': 'dianthus'},
    {'value': 492, 'name': 'Double Beans'},
    {'value': 495, 'name': 'Dragon fruit'},
    {'value': 423, 'name': 'dried mango'},
    {'value': 168, 'name': 'Drumstick'},
    {'value': 132, 'name': 'Dry Chillies'},
    {'value': 345, 'name': 'Dry Fodder'},
    {'value': 278, 'name': 'Dry Grapes'},
    {'value': 370, 'name': 'Duck'},
    {'value': 163, 'name': 'Duster Beans'},
    {'value': 367, 'name': 'Egg'},
    {'value': 361, 'name': 'Egypian Clover(Barseem)'},
    {'value': 296, 'name': 'Elephant Yam (Suran)'},
    {'value': 64, 'name': 'Field Pea'},
    {'value': 221, 'name': 'Fig(Anjura/Anjeer)'},
    {'value': 206, 'name': 'Firewood'},
    {'value': 366, 'name': 'Fish'},
    {'value': 510, 'name': 'Flax seeds'},
    {'value': 365, 'name': 'Flower Broom'},
    {'value': 121, 'name': 'Foxtail Millet(Navane)'},
    {'value': 298, 'name': 'French Beans (Frasbean)'},
    {'value': 350, 'name': 'Galgal(Lemon)'},
    {'value': 471, 'name': 'Gamphrena'},
    {'value': 25, 'name': 'Garlic'},
    {'value': 249, 'name': 'Ghee'},
    {'value': 452, 'name': 'Giloy'},
    {'value': 276, 'name': 'Gingelly Oil'},
    {'value': 27, 'name': 'Ginger(Dry)'},
    {'value': 103, 'name': 'Ginger(Green)'},
    {'value': 364, 'name': 'Gladiolus Bulb'},
    {'value': 363, 'name': 'Gladiolus Cut Flower'},
    {'value': 462, 'name': 'Glardia'},
    {'value': 219, 'name': 'Goat'},
    {'value': 353, 'name': 'Goat Hair'},
    {'value': 475, 'name': 'golden rod'},
    {'value': 511, 'name': 'Gond'},
    {'value': 494, 'name': 'Goose berry (Nellikkai)'},
    {'value': 359, 'name': 'Gram Raw(Chholia)'},
    {'value': 294, 'name': 'Gramflour'},
    {'value': 22, 'name': 'Grapes'},
    {'value': 165, 'name': 'Green Avare (W)'},
    {'value': 87, 'name': 'Green Chilli'},
    {'value': 346, 'name': 'Green Fodder'},
    {'value': 9, 'name': 'Green Gram (Moong)(Whole)'},
    {'value': 265, 'name': 'Green Gram Dal (Moong Dal)'},
    {'value': 50, 'name': 'Green Peas'},
    {'value': 267, 'name': 'Ground Nut Oil'},
    {'value': 268, 'name': 'Ground Nut Seed'},
    {'value': 10, 'name': 'Groundnut'},
    {'value': 314, 'name': 'Groundnut (Split)'},
    {'value': 312, 'name': 'Groundnut pods (raw)'},
    {'value': 75, 'name': 'Guar'},
    {'value': 413, 'name': 'Guar Seed(Cluster Beans Seed)'},
    {'value': 185, 'name': 'Guava'},
    {'value': 453, 'name': 'Gudmar'},
    {'value': 454, 'name': 'Guggal'},
    {'value': 461, 'name': 'gulli'},
    {'value': 74, 'name': 'Gur(Jaggery)'},
    {'value': 279, 'name': 'Gurellu'},
    {'value': 469, 'name': 'gypsophila'},
    {'value': 252, 'name': 'Haralekai'},
    {'value': 512, 'name': 'Harrah'},
    {'value': 216, 'name': 'He Buffalo'},
    {'value': 474, 'name': 'Heliconia species'},
    {'value': 369, 'name': 'Hen'},
    {'value': 125, 'name': 'Hippe Seed'},
    {'value': 236, 'name': 'Honey'},
    {'value': 124, 'name': 'Honge seed'},
    {'value': 119, 'name': 'Hybrid Cumbu'},
    {'value': 473, 'name': 'hydrangea'},
    {'value': 299, 'name': 'Indian Beans (Seam)'},
    {'value': 344, 'name': 'Indian Colza(Sarson)'},
    {'value': 465, 'name': 'Irish'},
    {'value': 256, 'name': 'Isabgul (Psyllium)'},
    {'value': 182, 'name': 'Jack Fruit'},
    {'value': 513, 'name': 'Jaee'},
    {'value': 406, 'name': 'Jaffri'},
    {'value': 151, 'name': 'Jaggery'},
    {'value': 175, 'name': 'Jamamkhan'},
    {'value': 184, 'name': 'Jamun(Narale Hannu)'},
    {'value': 376, 'name': 'Jarbara'},
    {'value': 229, 'name': 'Jasmine'},
    {'value': 250, 'name': 'Javi'},
    {'value': 5, 'name': 'Jowar(Sorghum)'},
    {'value': 16, 'name': 'Jute'},
    {'value': 210, 'name': 'Jute Seed'},
    {'value': 362, 'name': 'Kabuli Chana(Chickpeas-White)'},
    {'value': 317, 'name': 'Kacholam'},
    {'value': 230, 'name': 'Kakada'},
    {'value': 501, 'name': 'kakatan'},
    {'value': 456, 'name': 'Kalihari'},
    {'value': 457, 'name': 'Kalmegh'},
    {'value': 233, 'name': 'Kankambra'},
    {'value': 115, 'name': 'Karamani'},
    {'value': 439, 'name': 'karanja seeds'},
    {'value': 187, 'name': 'Karbuja(Musk Melon)'},
    {'value': 305, 'name': 'Kartali (Kantola)'},
    {'value': 481, 'name': 'Kevda'},
    {'value': 61, 'name': 'Kharif Mash'},
    {'value': 514, 'name': 'Khirni'},
    {'value': 372, 'name': 'Khoya'},
    {'value': 336, 'name': 'Kinnow'},
    {'value': 177, 'name': 'Knool Khol'},
    {'value': 117, 'name': 'Kodo Millet(Varagu)'},
    {'value': 458, 'name': 'kokum'},
    {'value': 459, 'name': 'Kooth'},
    {'value': 243, 'name': 'Kuchur'},
    {'value': 114, 'name': 'Kulthi(Horse Gram)'},
    {'value': 415, 'name': 'Kutki'},
    {'value': 426, 'name': 'kutki'},
    {'value': 155, 'name': 'Ladies Finger'},
    {'value': 515, 'name': 'Laha'},
    {'value': 96, 'name': 'Lak(Teora)'},
    {'value': 171, 'name': 'Leafy Vegetable'},
    {'value': 310, 'name': 'Lemon'},
    {'value': 63, 'name': 'Lentil (Masur)(Whole)'},
    {'value': 378, 'name': 'Lilly'},
    {'value': 180, 'name': 'Lime'},
    {'value': 470, 'name': 'Limonia (status)'},
    {'value': 67, 'name': 'Linseed'},
    {'value': 280, 'name': 'Lint'},
    {'value': 432, 'name': 'liquor turmeric'},
    {'value': 351, 'name': 'Litchi'},
    {'value': 302, 'name': 'Little gourd (Kundru)'},
    {'value': 304, 'name': 'Long Melon(Kakri)'},
    {'value': 403, 'name': 'Lotus'},
    {'value': 339, 'name': 'Lotus Sticks'},
    {'value': 337, 'name': 'Lukad'},
    {'value': 479, 'name': 'Lupine'},
    {'value': 504, 'name': 'Ma.Inji'},
    {'value': 107, 'name': 'Mace'},
    {'value': 427, 'name': 'macoy'},
    {'value': 411, 'name': 'Mahedi'},
    {'value': 335, 'name': 'Mahua'},
    {'value': 371, 'name': 'Mahua Seed(Hippe seed)'},
    {'value': 288, 'name': 'Maida Atta'},
    {'value': 4, 'name': 'Maize'},
    {'value': 20, 'name': 'Mango'},
    {'value': 172, 'name': 'Mango (Raw-Ripe)'},
    {'value': 422, 'name': 'mango powder'},
    {'value': 225, 'name': 'Maragensu'},
    {'value': 181, 'name': 'Marasebu'},
    {'value': 407, 'name': 'Marget'},
    {'value': 235, 'name': 'Marigold(Calcutta)'},
    {'value': 405, 'name': 'Marigold(loose)'},
    {'value': 502, 'name': 'Marikozhunthu'},
    {'value': 60, 'name': 'Mash'},
    {'value': 340, 'name': 'Mashrooms'},
    {'value': 259, 'name': 'Masur Dal'},
    {'value': 93, 'name': 'Mataki'},
    {'value': 47, 'name': 'Methi Seeds'},
    {'value': 46, 'name': 'Methi(Leaves)'},
    {'value': 237, 'name': 'Millets'},
    {'value': 360, 'name': 'Mint(Pudina)'},
    {'value': 258, 'name': 'Moath Dal'},
    {'value': 95, 'name': 'Moath Dal'},
    {'value': 77, 'name': 'Mousambi(Sweet Lime)'},
    {'value': 446, 'name': 'Muesli'},
    {'value': 428, 'name': 'Muleti'},
    {'value': 516, 'name': 'Muskmelon Seeds'},
    {'value': 12, 'name': 'Mustard'},
    {'value': 324, 'name': 'Mustard Oil'},
    {'value': 142, 'name': 'Myrobolan(Harad)'},
    {'value': 245, 'name': 'Nargasi'},
    {'value': 222, 'name': 'Nearle Hannu'},
    {'value': 126, 'name': 'Neem Seed'},
    {'value': 223, 'name': 'Nelli Kai'},
    {'value': 500, 'name': 'Nerium'},
    {'value': 445, 'name': 'nigella seeds'},
    {'value': 424, 'name': 'nigella seeds'},
    {'value': 98, 'name': 'Niger Seed (Ramtil)'},
    {'value': 106, 'name': 'Nutmeg'},
    {'value': 23, 'name': 'Onion'},
    {'value': 358, 'name': 'Onion Green'},
    {'value': 18, 'name': 'Orange'},
    {'value': 381, 'name': 'Orchid'},
    {'value': 420, 'name': 'Other green and fresh vegetables'},
    {'value': 97, 'name': 'Other Pulses'},
    {'value': 213, 'name': 'Ox'},
    {'value': 414, 'name': 'Paddy(Dhan)(Basmati)'},
    {'value': 2, 'name': 'Paddy(Dhan)(Common)'},
    {'value': 441, 'name': 'Palash flowers'},
    {'value': 72, 'name': 'Papaya'},
    {'value': 313, 'name': 'Papaya (Raw)'},
    {'value': 404, 'name': 'Patti Calcutta'},
    {'value': 331, 'name': 'Peach'},
    {'value': 330, 'name': 'Pear(Marasebu)'},
    {'value': 308, 'name': 'Peas cod'},
    {'value': 174, 'name': 'Peas Wet'},
    {'value': 347, 'name': 'Peas(Dry)'},
    {'value': 301, 'name': 'Pegeon Pea (Arhar Fali)'},
    {'value': 109, 'name': 'Pepper garbled'},
    {'value': 110, 'name': 'Pepper ungarbled'},
    {'value': 489, 'name': 'Perandai'},
    {'value': 327, 'name': 'Persimon(Japani Fal)'},
    {'value': 220, 'name': 'Pigs'},
    {'value': 21, 'name': 'Pineapple'},
    {'value': 431, 'name': 'pippali'},
    {'value': 329, 'name': 'Plum'},
    {'value': 303, 'name': 'Pointed gourd (Parval)'},
    {'value': 240, 'name': 'Polherb'},
    {'value': 190, 'name': 'Pomegranate'},
    {'value': 425, 'name': 'Poppy capsules'},
    {'value': 421, 'name': 'poppy seeds'},
    {'value': 24, 'name': 'Potato'},
    {'value': 84, 'name': 'Pumpkin'},
    {'value': 254, 'name': 'Pundi'},
    {'value': 128, 'name': 'Pundi Seed'},
    {'value': 447, 'name': 'Pupadia'},
    {'value': 161, 'name': 'Raddish'},
    {'value': 30, 'name': 'Ragi (Finger Millet)'},
    {'value': 409, 'name': 'Raibel'},
    {'value': 248, 'name': 'Rajgir'},
    {'value': 517, 'name': 'Rala'},
    {'value': 282, 'name': 'Ram'},
    {'value': 518, 'name': 'Ramphal'},
    {'value': 307, 'name': 'Rat Tail Radish (Mogari)'},
    {'value': 460, 'name': 'Ratanjot'},
    {'value': 65, 'name': 'Raya'},
    {'value': 519, 'name': 'Rayee'},
    {'value': 493, 'name': 'Red Cabbage'},
    {'value': 7, 'name': 'Red Gram'},
    {'value': 322, 'name': 'Resinwood'},
    {'value': 62, 'name': 'Riccbcan'},
    {'value': 3, 'name': 'Rice'},
    {'value': 160, 'name': 'Ridgeguard(Tori)'},
    {'value': 374, 'name': 'Rose(Local)'},
    {'value': 228, 'name': 'Rose(Loose))'},
    {'value': 373, 'name': 'Rose(Tata)'},
    {'value': 306, 'name': 'Round gourd'},
    {'value': 111, 'name': 'Rubber'},
    {'value': 291, 'name': 'Sabu Dan'},
    {'value': 59, 'name': 'Safflower'},
    {'value': 338, 'name': 'Saffron'},
    {'value': 271, 'name': 'Sajje'},
    {'value': 468, 'name': 'salvia'},
    {'value': 122, 'name': 'Same/Savi'},
    {'value': 433, 'name': 'sanay'},
    {'value': 450, 'name': 'Sandalwood'},
    {'value': 247, 'name': 'Sarasum'},
    {'value': 277, 'name': 'Season Leaves'},
    {'value': 253, 'name': 'Seegu'},
    {'value': 176, 'name': 'Seemebadnekai'},
    {'value': 201, 'name': 'Seetapal'},
    {'value': 11, 'name': 'Sesamum(Sesame,Gingelly,Til)'},
    {'value': 464, 'name': 'sevanti'},
    {'value': 217, 'name': 'She Buffalo'},
    {'value': 283, 'name': 'She Goat'},
    {'value': 218, 'name': 'Sheep'},
    {'value': 183, 'name': 'Siddota'},
    {'value': 490, 'name': 'Siru Kizhagu'},
    {'value': 226, 'name': 'Skin And Hide'},
    {'value': 156, 'name': 'Snakeguard'},
    {'value': 135, 'name': 'Soanf'},
    {'value': 207, 'name': 'Soapnut(Antawala/Retha)'},
    {'value': 520, 'name': 'Soha'},
    {'value': 286, 'name': 'Soji'},
    {'value': 246, 'name': 'Sompu'},
    {'value': 13, 'name': 'Soyabean'},
    {'value': 455, 'name': 'spikenard'},
    {'value': 342, 'name': 'Spinach'},
    {'value': 311, 'name': 'Sponge gourd'},
    {'value': 332, 'name': 'Squash(Chappal Kadoo)'},
    {'value': 440, 'name': 'stevia'},
    {'value': 430, 'name': 'stone pulverizer'},
    {'value': 48, 'name': 'Sugar'},
    {'value': 150, 'name': 'Sugarcane'},
    {'value': 488, 'name': 'Sundaikai'},
    {'value': 14, 'name': 'Sunflower'},
    {'value': 285, 'name': 'Sunflower Seed'},
    {'value': 139, 'name': 'Sunhemp'},
    {'value': 242, 'name': 'Suram'},
    {'value': 300, 'name': 'Surat Beans (Papadi)'},
    {'value': 255, 'name': 'Suva (Dill Seed)'},
    {'value': 178, 'name': 'Suvarna Gadde'},
    {'value': 152, 'name': 'Sweet Potato'},
    {'value': 173, 'name': 'Sweet Pumpkin'},
    {'value': 466, 'name': 'Sweet Sultan'},
    {'value': 477, 'name': 'sweet william'},
    {'value': 120, 'name': 'T.V. Cumbu'},
    {'value': 261, 'name': 'Tamarind Fruit'},
    {'value': 208, 'name': 'Tamarind Seed'},
    {'value': 100, 'name': 'Tapioca'},
    {'value': 76, 'name': 'Taramira'},
    {'value': 44, 'name': 'Tea'},
    {'value': 200, 'name': 'Tender Coconut'},
    {'value': 116, 'name': 'Thinai (Italian Millet)'},
    {'value': 170, 'name': 'Thogrikai'},
    {'value': 162, 'name': 'Thondekai'},
    {'value': 349, 'name': 'Tinda'},
    {'value': 141, 'name': 'Tobacco'},
    {'value': 78, 'name': 'Tomato'},
    {'value': 323, 'name': 'Torchwood'},
    {'value': 66, 'name': 'Toria'},
    {'value': 234, 'name': 'Tube Flower'},
    {'value': 401, 'name': 'Tube Rose(Double)'},
    {'value': 408, 'name': 'Tube Rose(Loose)'},
    {'value': 377, 'name': 'Tube Rose(Single)'},
    {'value': 503, 'name': 'Tulasi'},
    {'value': 463, 'name': 'tulip'},
    {'value': 39, 'name': 'Turmeric'},
    {'value': 309, 'name': 'Turmeric (raw)'},
    {'value': 341, 'name': 'Turnip'},
    {'value': 436, 'name': 'vadang'},
    {'value': 437, 'name': 'Vatsanabha'},
    {'value': 343, 'name': 'Walnut'},
    {'value': 496, 'name': 'Water Apple'},
    {'value': 521, 'name': 'Water chestnut'},
    {'value': 73, 'name': 'Water Melon'},
    {'value': 522, 'name': 'Wax'},
    {'value': 1, 'name': 'Wheat'},
    {'value': 287, 'name': 'Wheat Atta'},
    {'value': 429, 'name': 'White Muesli'},
    {'value': 412, 'name': 'White Peas'},
    {'value': 158, 'name': 'White Pumpkin'},
    {'value': 498, 'name': 'Wild lemon'},
    {'value': 203, 'name': 'Wood'},
    {'value': 499, 'name': 'Wood Apple'},
    {'value': 348, 'name': 'Wool'},
    {'value': 244, 'name': 'Yam'},
    {'value': 297, 'name': 'Yam (Ratalu)'}
]

state = [
    {'value':'KL', 'name' :'Kerala'},
    {'value':'MH', 'name' :'Maharashtra'},
    {'value':'UP', 'name' :'Uttar Pradesh'},
    {'value':'DL', 'name' :'NCT of Delhi'},
]